                <div class="admin__field">
                    <label class="admin__field-label"></label>
                    <div class="admin__field-control">
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action submit primary" title="Trimite mesajul">
                                    <span>Filtreaza</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</form>
