<form class="form" action="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\Data\Form\FormKey')->getFormKey(); ?>" />
    <div class="fieldset-wrapper">
        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field">
                    <label for="phone" class="admin__field-label">
                        <span>Perioada start</span>
                    </label>

                    <div class="admin__field-control">
                        <input type="text" id="sendsms_period_start" name="sendsms_period_start" class="admin__control-text" />
                    </div>
                </div>
                <div class="admin__field">
                    <label for="phone" class="admin__field-label">
                        <span>Perioada final</span>
                    </label>

                    <div class="admin__field-control">
                        <input type="text" id="sendsms_period_end" name="sendsms_period_end" class="admin__control-text" />
                    </div>
                </div>
                <div class="admin__field">
                    <label for="phone" class="admin__field-label">
                        <span>Suma minima pe comanda</span>
                    </label>

                    <div class="admin__field-control">
                        <input type="text" id="sendsms_sum" name="sendsms_sum" class="admin__control-text" value="0">
                    </div>
                </div>
