<form class="form" action="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\Data\Form\FormKey')->getFormKey(); ?>" />
    <div class="fieldset-wrapper">
        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <hr />
                <h4>Trimite SMS</h4>
                <div class="admin__field">
                    <label for="message" class="admin__field-label">
                        <span>Mesaj</span>
                    </label>

                    <div class="admin__field-control">
                        <textarea id="message" name="message" class="admin__control-textarea" required><?php echo $this->getOrder()->getRealOrderId(); ?></textarea>
                        <p class="sendsms-char-count">160 caractere ramase</p>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label"></label>
                    <div class="admin__field-control">
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action submit primary" title="Trimite mesajul">
                                    <span>Trimite mesaj</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</form>
<hr />
